"""State machine states and reason codes."""
from enum import Enum


class RequestState(str, Enum):
    REQUEST_RECEIVED = "REQUEST_RECEIVED"
    PLANNER_DECIDED = "PLANNER_DECIDED"
    QA_RETRIEVAL_DONE = "QA_RETRIEVAL_DONE"
    QA_ANSWER_DRAFTED = "QA_ANSWER_DRAFTED"
    QA_VERIFIED_PASS = "QA_VERIFIED_PASS"
    QA_VERIFIED_FAIL = "QA_VERIFIED_FAIL"
    SC_ATTEMPT_CREATED = "SC_ATTEMPT_CREATED"
    SC_ANSWERS_SUBMITTED = "SC_ANSWERS_SUBMITTED"
    SC_EVALUATED = "SC_EVALUATED"
    INVALID_EVALUATION = "INVALID_EVALUATION"
    # Terminal
    RESPONSE_SENT = "RESPONSE_SENT"
    REFUSAL_SENT = "REFUSAL_SENT"
    CLARIFICATION_REQUESTED = "CLARIFICATION_REQUESTED"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"


class PlannerRoute(str, Enum):
    QA = "qa"
    SELF_CHECK = "self_check"
    CLARIFICATION = "clarification"


class RefusalReasonCode(str, Enum):
    LOW_EVIDENCE = "LOW_EVIDENCE"
    NO_CITATIONS = "NO_CITATIONS"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    OFF_TOPIC = "OFF_TOPIC"


class ErrorReasonCode(str, Enum):
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_ERROR = "LLM_ERROR"
    RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
